#MySql 세팅
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/giantstepstudyboard?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 9071

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.springframework.boot.autoconfigure: ERROR

